### PR TITLE
added patterns to file names

### PR DESCRIPTION
**Pull request by mr47**
Added special feature that requested on windows machines, so we can you a glob patterns.

It's pretty straightforward, if any question write me here.

Thanks!

### CODE REVIEW

**Comment by meriadec** [comment]
thanks @mr47

**Comment by meriadec** [comment]
Hmm I merged a bit too fast, it isn't working as it is currently because you added a github reference (to mr47/cross-env) in package.json, and it's not containing the `cross-env` executable. So using `yarn && yarn build` results in a crash. Also, I think it's better if this repo depends on the official cross-env, to get updates, etc.

Using [rimraf](https://github.com/isaacs/rimraf) will do the trick for the `npm run build` script, but I got no solution on cmd for `chmod` on Windows. I usually advise people to install [git-bash for Windows](https://git-scm.com/downloads) or [cygwin](https://www.cygwin.com/) to have access to some basic UNIX commands like `chmod` or `rm`.

So I'm reverting this for now, but the glob thing is definitely a good point. Would you mind creating a PR containing only the glob addition? Thanks !

**Comment by mr47** [comment]
@meriadec I am waiting to get merged my PR to `cross-env`, so in a while i can remove my version of `cross-env`

Thanks!

**Comment by mr47** [comment]
@meriadec updated my branch, removed cross-env

Cheers!

**Pull request merged**
